title: Base de solutions la Boussole
description: Liste des solutions intégrées à la Boussole
theme: jekyll-theme-clean-blog

url: https://aaalleno.github.io

aux_links:
  La Boussole: https://boussole.onrender.com
